version: "3.8"

services:
  mysql-db:
    image: mysql
    container_name: obligatorio_arq
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=obligatorio_arq
    ports:
      - "3306:3306"
    networks:
      - obligatorio_arq
    volumes:
      - mysql-data:/var/lib/mysql

  redis_service:
    image: redis
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - obligatorio_arq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  
    networks:
      - obligatorio_arq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret

  app:
    build:
      context: .
    container_name: obligatorio_app
    ports:
      - "3001:3001"
    networks:
      - obligatorio_arq
    environment:
      - DB_HOST=mysql-db
      - REDIS_HOST=redis_service
      - PORT=3001
      - NODE_ENV=development
    depends_on:
      - mysql-db
      - redis_service

volumes:
  mysql-data:

networks:
  obligatorio_arq:
    driver: bridge
