version: "3.8"

services:
  mysql-db:
    image: mysql
    container_name: obligatorio_arq
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=obligatorio_arq
    ports:
      - "3306:3306"
    networks:
      - obligatorio_arq
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - obligatorio_arq

  app:
    build:
      context: .
    container_name: obligatorio_app
    ports:
      - "3000:3000"
    networks:
      - obligatorio_arq
    environment:
      - DB_HOST=mysql-db
      - REDIS_HOST=redis_service
      - PORT=3000
      - NODE_ENV=development

volumes:
  mysql-data:

networks:
  obligatorio_arq:
